#application
server:
  port: 50200
  tomcat.threads.max: 20

spring:
  main:
    lazy-initialization: true
  application:
    name: book-service
  jackson:
    default-property-inclusion: NON_NULL
    jackson:
      default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    url: jdbc:postgresql://localhost:31432/golo-book-service-db
    username: ${DB_USERNAME:golo}
    password: ${DB_PASSWORD:qFkJj92N9A4E}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: TRACE

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    filter: true
    path: /swagger-ui/index.html


#import
import.delimiter: ";"
import.batchSize: 100
