#application
server:
  port: 40277
  tomcat.threads.max: 20

spring:
  main:
    lazy-initialization: true

  application:
    name: book-service


springdoc.swagger-ui.path: /swagger-ui/index.html
springdoc.enable-native-support: "true"


#database
spring.datasource.url: jdbc:postgresql://localhost:30432/golo-book-service-db
spring.datasource.username: ${DB_USERNAME:golo}
spring.datasource.password: ${DB_PASSWORD:qFkJj92N9A4E}


#spring.jpa.show-sql: true
#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true

spring.servlet.multipart.max-file-size: 25MB
spring.servlet.multipart.max-request-size: 25MB

#import
import.delimiter: ";"
import.batchSize: 100
